# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5aaded2899d449156c5deb413cb205f3"
name = "form-app-testttt"
application_url = "https://towers-marvel-cdna-researcher.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products , write_app_proxy"

[app_proxy]
url = "/configurator"
prefix = "apps"
subpath = "configurator"

[auth]
redirect_urls = [
    "https://towers-marvel-cdna-researcher.trycloudflare.com/api/auth",
]

